apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: images-gallery
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL2FkbWluOmFkbWluQHBvc3RncmVzcWwtc2VydmljZTo1NDMyL2ltYWdlc19nYWxsZXJ5
  postgres-user: YWRtaW4=
  postgres-password: YWRtaW4=
